apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-learning-platform.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8787
