{{- if .Values.backend.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secret.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
{{- range $k, $v := .Values.backend.secret.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
