apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-learning-platform.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
